### PR TITLE
retry on network failure for detecting EC2

### LINKED ISSUE #395: CloudWatch agent stops sending custom metrics after an instance running CentOS 8 or RedHat 8 is rebooted
#298 was made originally to address this issue, wherein a RHEL8 or CentOS 8 host would fail to publish metrics after a reboot because the CloudWatch agent would start prior to network availability. This causes the agent to assume that it is on-prem. Putting in the change #344 causes issues for other setups. 

#344 should be reverted, and a different solution should be implemented to fix the CentOS reboot issue.

### PR DESCRIPTION
**Pull request by SaxyPandaBear**
# Description of the issue
Closes #395 

# Description of changes
Add a simple retry in the EC2 util so that if the network is not immediately available, it can recover gracefully once network is available.

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

# Tests
1. Reproduced issue on a CentOS 8 EC2 instance with the 349 version of the agent
2. Confirmed that the network target change in #344 with v350 fixes the issue
3. Ran locally built agent and config-translator binary on the host, after reverting the systemd configuration change
4. Output below shows that at initial startup, the host could not connect to EC2 metadata after the reboot, but recovered after one retry: `2022/03/08 17:51:05 I! 2022/03/08 17:51:04 E! [EC2] network not available yet. Sleeping for 1 second`
```
[centos@ip-172-31-59-92 ~]$ cat /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log 
2022/03/08 17:50:08 I! I! Detected the instance is EC2
2022/03/08 17:50:08 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json ...
/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json does not exist or cannot read. Skipping it.
2022/03/08 17:50:08 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/default ...
Valid Json input schema.
I! Detecting run_as_user...
No csm configuration found.
No log configuration found.
Configuration validation first phase succeeded
 
2022/03/08 17:50:08 I! Config has been translated into TOML /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml 
2022/03/08 17:50:08 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json ...
2022/03/08 17:50:08 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/default ...
2022/03/08 17:50:08 I! Detected runAsUser: cwagent
2022/03/08 17:50:08 I! Changing ownership of [/opt/aws/amazon-cloudwatch-agent/logs /opt/aws/amazon-cloudwatch-agent/etc /opt/aws/amazon-cloudwatch-agent/var] to 990:987
2022/03/08 17:50:08 I! Set HOME: /home/cwagent
2022-03-08T17:50:08Z I! Starting AmazonCloudWatchAgent 1.247350.0-15-g98cf13bb-dirty
2022-03-08T17:50:08Z I! AWS SDK log level not set
2022-03-08T17:50:08Z I! Loaded inputs: disk mem
2022-03-08T17:50:08Z I! Loaded aggregators: 
2022-03-08T17:50:08Z I! Loaded processors: ec2tagger
2022-03-08T17:50:08Z I! Loaded outputs: cloudwatch
2022-03-08T17:50:08Z I! Tags enabled: host=ip-172-31-59-92.us-west-2.compute.internal
2022-03-08T17:50:08Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"ip-172-31-59-92.us-west-2.compute.internal", Flush Interval:1s
2022-03-08T17:50:08Z I! [logagent] starting
2022-03-08T17:50:08Z I! [processors.ec2tagger] ec2tagger: EC2 tagger has started initialization.
2022-03-08T17:50:08Z I! cloudwatch: get unique roll up list []
2022-03-08T17:50:08Z I! cloudwatch: publish with ForceFlushInterval: 1m0s, Publish Jitter: 41s
2022-03-08T17:50:08Z I! [processors.ec2tagger] ec2tagger: Initial retrieval of tags succeded
2022-03-08T17:50:08Z I! [processors.ec2tagger] ec2tagger: EC2 tagger has started, finished initial retrieval of tags and Volumes
2022-03-08T17:50:41Z I! Profiler is stopped during shutdown
2022-03-08T17:50:41Z I! [agent] Hang on, flushing any cached metrics before shutdown
2022/03/08 17:51:05 I! 2022/03/08 17:51:04 E! [EC2] network not available yet. Sleeping for 1 second
I! Detected the instance is EC2
2022/03/08 17:51:05 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json ...
/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json does not exist or cannot read. Skipping it.
2022/03/08 17:51:05 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/default ...
Valid Json input schema.
I! Detecting run_as_user...
No csm configuration found.
No log configuration found.
Configuration validation first phase succeeded
 
2022/03/08 17:51:05 I! Config has been translated into TOML /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml 
2022/03/08 17:51:05 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json ...
2022/03/08 17:51:05 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/default ...
2022/03/08 17:51:05 I! Detected runAsUser: cwagent
2022/03/08 17:51:05 I! Changing ownership of [/opt/aws/amazon-cloudwatch-agent/logs /opt/aws/amazon-cloudwatch-agent/etc /opt/aws/amazon-cloudwatch-agent/var] to 990:987
2022/03/08 17:51:05 I! Set HOME: /home/cwagent
2022-03-08T17:51:08Z I! Starting AmazonCloudWatchAgent 1.247350.0-15-g98cf13bb-dirty
2022-03-08T17:51:08Z I! AWS SDK log level not set
2022-03-08T17:51:08Z I! Loaded inputs: disk mem
2022-03-08T17:51:08Z I! Loaded aggregators: 
2022-03-08T17:51:08Z I! Loaded processors: ec2tagger
2022-03-08T17:51:08Z I! Loaded outputs: cloudwatch
2022-03-08T17:51:08Z I! Tags enabled: host=ip-172-31-59-92.us-west-2.compute.internal
2022-03-08T17:51:08Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"ip-172-31-59-92.us-west-2.compute.internal", Flush Interval:1s
2022-03-08T17:51:08Z I! [logagent] starting
2022-03-08T17:51:08Z I! [processors.ec2tagger] ec2tagger: EC2 tagger has started initialization.
2022-03-08T17:51:08Z I! cloudwatch: get unique roll up list []
2022-03-08T17:51:08Z I! cloudwatch: publish with ForceFlushInterval: 1m0s, Publish Jitter: 42s
2022-03-08T17:51:08Z I! [processors.ec2tagger] ec2tagger: Initial retrieval of tags succeded
2022-03-08T17:51:08Z I! [processors.ec2tagger] ec2tagger: EC2 tagger has started, finished initial retrieval of tags and Volumes
```

### CODE REVIEW

File: translator/util/ec2util/ec2util.go [hunk 1]
```diff
@@ -43,6 +46,14 @@ func initEC2UtilSingleton() (newInstance *ec2Util) {
 		return
 	}
 	md := ec2metadata.New(ses)
+	for i := 0; i < allowedRetries; i++ {
```
Comment (ZhenyuTan-amz) [inline translator/util/ec2util/ec2util.go:49]: My concern with this fix is 
1. how do we know 3 retries is enough for network getting online for those customers used to have this issue? Is 3 seconds long enough?
2. Will this 3 seconds(or potentially longer if we figured we need to wait more) delay for on-prem customers break any experience? Like on-prem customer missing 3 secs of metrics, which could be valuable during a launch.

Comment (sethAmazon) [reply translator/util/ec2util/ec2util.go:49]: Maybe this can be configurable.

Comment (SaxyPandaBear) [reply translator/util/ec2util/ec2util.go:49]: I considered making the retries configurable. I'm not opposed to it. 3 was an arbitrary number. Originally I tested with 10 as the retries. My push back would be if the EC2 instance takes longer than 3 seconds for network activity then there are probably other issues going on with the host/OS. 

With the on-prem impact, I think that's a valid concern. But there is already a way for users to mitigate that by specifying on-prem mode themselves, which short circuits before we try to connect to the EC2 metadata endpoint. I don't think it's ideal, but currently not sure how else to implement this that would not require any change for people running on-prem and using auto detection.

Comment (ZhenyuTan-amz) [reply translator/util/ec2util/ec2util.go:49]: If I'm reading the right code at https://github.com/aws/amazon-cloudwatch-agent/blob/master/translator/util/sdkutil.go#L35 customer can config in EC2 and short circuits, but no on-prem, I didn't find anywhere a onPrem flag can bypass this method DetectAgentMode with my quick search.

Comment (SaxyPandaBear) [reply translator/util/ec2util/ec2util.go:49]: Let me dig into that a little more. I was really only looking at 
```go
	if context.CurrentContext().Mode() == config.ModeOnPrem {
		return
	}
```
inside of the `initEC2UtilSingleton` function.

Comment (SaxyPandaBear) [reply translator/util/ec2util/ec2util.go:49]: Looking at where it gets called, in the translator, 
```go
var inputMode = flag.String("mode", "ec2", "Please provide the mode, i.e. ec2, onPrem")
```
The default value for the flag in the translator is `ec2`. Then in the `DetectAgentMode` function,
```go
if configuredMode != "auto" {
    return configuredMode
}
```
if the input mode is not `auto`, then it immediately returns that string. 

The `start-amazon-cloudwatch-agent` binary runs the translator with the mode set to auto ☹️ so you're right. 

Personally, I think that the simplest way to resolve this is to extend the if statement to also check for a negative (non-empty) value from the environment if it is running in AWS 🤔 
```go
if runInAws == config.RUN_IN_AWS_TRUE {
    fmt.Println("I! Detected from ENV instance is EC2")
    return config.ModeEC2
} else if runInAws == config.RUN_IN_AWS_FALSE {
    fmt.Println("I! Detected from ENV instance is OnPrem")
    return config.ModeOnPrem
}
```

Thoughts?

Comment (ZhenyuTan-amz) [reply translator/util/ec2util/ec2util.go:49]: Currently, not-in-aws == onPrem, as long as this does not default to false, that should works.

Comment (SaxyPandaBear) [reply translator/util/ec2util/ec2util.go:49]: `runInAws` is derived from the environment, and `os.Getenv()` defaults to the empty string. If we introduced a const like:
```go
RUN_IN_AWS_FALSE = "False"
```
we could check against a non-empty value, so that wouldn't impact existing configuration. Would still love to hear any suggestions for how to account for this without impacting existing users who are on-prem and don't want to modify their environment, though - I still haven't thought of how to.

File: translator/util/ec2util/ec2util.go [hunk 2]
```diff
@@ -43,6 +46,14 @@ func initEC2UtilSingleton() (newInstance *ec2Util) {
...
+		if md.Available() {
+			continue
```
Comment (adam-mateen) [inline translator/util/ec2util/ec2util.go:51]: I think `break` makes more sense than `continue`.
If it is available on the first loop, we do not need to loop anymore.

Comment (SaxyPandaBear) [reply translator/util/ec2util/ec2util.go:51]: Oops that's my bad. I meant to use `break` here.

File: translator/util/ec2util/ec2util.go (hunk 1 above)
Comment (SaxyPandaBear) [reply translator/util/ec2util/ec2util.go:48]: Going to update this. Pivoting from the implementation here that introduces a rudimentary retry when the network is not available and we try to check for IMDS, because @ZhenyuTan-amz is right and we shouldn't add the retry for the case where a host should not interact with IMDS because it's not hosted on AWS.

New approach is to use the `net` package to iterate over the network interfaces on the host, and block until there is a non-loopback network interface that is `up`. This should help safeguard (at least a little bit) for the scenario where the host is on-prem, and doesn't need to check the IMDS endpoint.

Comment (SaxyPandaBear) [reply translator/util/ec2util/ec2util.go:48]: Tested it on my MacBook (on-prem) and saw that it did not attempt to sleep after finding active network access.
```
3c22fbe51e1b:bin andhuy$ sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m auto -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s
/opt/aws/amazon-cloudwatch-agent/bin/config-downloader --output-dir /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d --download-source file:/opt/aws/amazon-cloudwatch-agent/bin/config.json --mode auto --config /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml --multi-config default
2022/03/09 09:49:24 Name: lo0, Flags: up|loopback|multicast
2022/03/09 09:49:24 Name: gif0, Flags: pointtopoint|multicast
2022/03/09 09:49:24 Name: stf0, Flags: 0
2022/03/09 09:49:24 Name: en6, Flags: up|broadcast|multicast
2022/03/09 09:49:24 E! ec2metadata is not available
I! Detected the instance is OnPrem
Got Home directory: /var/root
I! Set home dir Linux: /var/root
I! SDKRegionWithCredsMap region:  us-east-1
Successfully fetched the config and saved in /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/file_config.json.tmp
/opt/aws/amazon-cloudwatch-agent/bin/config-translator --input /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json --input-dir /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d --output /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml --mode auto --config /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml --multi-config default
2022/03/09 09:49:24 Name: lo0, Flags: up|loopback|multicast
2022/03/09 09:49:24 Name: gif0, Flags: pointtopoint|multicast
2022/03/09 09:49:24 Name: stf0, Flags: 0
2022/03/09 09:49:24 Name: en6, Flags: up|broadcast|multicast
2022/03/09 09:49:25 E! ec2metadata is not available
I! Detected the instance is OnPrem
2022/03/09 09:49:25 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/file_config.json.tmp ...
Valid Json input schema.
Got Home directory: /var/root
I! Set home dir Linux: /var/root
I! SDKRegionWithCredsMap region:  us-east-1
No csm configuration found.
Under path : /logs/ | Info : Got hostname 3c22fbe51e1b.ant.amazon.com as log_stream_name
Configuration validation first phase succeeded
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent -schematest -config /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml
Configuration validation second phase succeeded
Configuration validation succeeded
```

File: translator/util/ec2util/ec2util.go [hunk 3]
```diff
@@ -37,39 +40,69 @@ func initEC2UtilSingleton() (newInstance *ec2Util) {
...
+	networkUp := false
+	for retry := 0; !networkUp && retry < allowedRetries; retry++ {
+		ifs, err := net.Interfaces()
+
+		if err != nil {
+			log.Println("E! [EC2] An error occurred while fetching network interfaces: ", err)
+		}
+
+		for _, in := range ifs {
+			if (in.Flags&net.FlagUp) != 0 && (in.Flags&net.FlagLoopback) == 0 {
```
Comment (adam-mateen) [inline translator/util/ec2util/ec2util.go:55]: I was going to say I don't like the style of "no space around the ampersand (&)", but that is probably just what gofmt does so I can't complain.

Comment (SaxyPandaBear) [reply translator/util/ec2util/ec2util.go:55]: I didn't like it either, but this is what Goland was doing by default. I can update it. Not sure if `gofmt` would revert it, so I'll check that too I guess

Comment (SaxyPandaBear) [reply translator/util/ec2util/ec2util.go:55]: `go fmt ./translator/util/ec2util/` removed the spaces that I reintroduced, so I guess we're stuck unless we want to override that specific behavior. Not sure if it's worth doing

**Review by adam-mateen — APPROVED** [review]
Approved.
Can you do a manual test on 1 windows server to make sure the "net" package does see a non loopback network interface and that the FlagUp behaves as expected.

Since "net" is a builtin package I am pretty sure it will work, but I'd feel better knowing we did a quick test.

File: translator/util/ec2util/ec2util.go (hunk 3 above)
Comment (adam-mateen) [reply translator/util/ec2util/ec2util.go:55]: If we do a lot of setting and checking of bits we could add helper functions like:
https://yourbasic.org/golang/bitmask-flag-set-clear/
Not suggesting it needs to be done now, just keep it in mind.

**Comment by SaxyPandaBear** [comment]
Will do

**Comment by SaxyPandaBear** [comment]
Windows EC2:
```
PS C:\Users\Administrator\Desktop> & "C:\Program Files\Amazon\AmazonCloudWatchAgent\amazon-cloudwatch-agent-ctl.ps1" -a fetch-config -m auto -s -c default
****** processing amazon-cloudwatch-agent ******
2022/03/09 16:24:13 Name: Ethernet 2, Flags: up|broadcast|multicast
Successfully fetched the config and saved in C:\ProgramData\Amazon\AmazonCloudWatchAgent\Configs\default.tmp
Start configuration validation...
2022/03/09 16:24:14 Reading json config file path: C:\ProgramData\Amazon\AmazonCloudWatchAgent\Configs\default.tmp ...
Valid Json input schema.
2022/03/09 16:24:14 Name: Ethernet 2, Flags: up|broadcast|multicast
No csm configuration found.
No log configuration found.
Configuration validation first phase succeeded
Configuration validation second phase succeeded
Configuration validation succeeded
AmazonCloudWatchAgent has been stopped
AmazonCloudWatchAgent has been started
PS C:\Users\Administrator\Desktop>
```
