### PR TITLE
Fix failing windows event log unit test.

### LINKED ISSUE #351: Windows event log tests regression in GitHub windows-2022 test runner image
Windows event log unit tests are failing consistently in GitHub Actions.
Example below:
```
--- FAIL: TestReadWithBothSources (2.04s)
    wineventlog_test.go:122: seekToEnd() current count 0
    wineventlog_test.go:128: seekToEnd() total 0
    wineventlog_test.go:175: 
        	Error Trace:	wineventlog_test.go:175
        	            				wineventlog_test.go:110
        	Error:      	Not equal: 
        	            	expected: 10
        	            	actual  : 0
        	Test:       	TestReadWithBothSources
Error:  	Messages:   	expected [Application] [ERROR] [777] [CWA_UnitTest111] , 10, actual 0
FAIL
```
I _think_ that this is attributed to a recent change to the Windows OS that GitHub is using for the runner: https://github.com/actions/virtual-environments/issues/4856

What corroborates that these failures are related to the GitHub runner change is that there are recent workflows that succeeded.

https://github.com/aws/amazon-cloudwatch-agent/runs/5009246587?check_suite_focus=true is a recent PR run that succeeded, which uses the Windows Server 2019 image.

https://github.com/aws/amazon-cloudwatch-agent/runs/5030533176?check_suite_focus=true is a recent failed run, which uses the Windows Server 2022 image. Though not 100% sure the issue, it's the only real change that would have affected the tests from what I can tell. 

I think what should be done is:
1. Update the workflow right now to use the `windows-2019` image for the test runner - the linked GitHub issue indicates that Windows Server 2019 is still supported, but not the default.
2. Triage the test failures in a separate, later PR on Windows Server 2022.

### PR DESCRIPTION
**Pull request by adam-mateen**
# Description of the issue
Fixes #351 
Fix failing windows event log unit test.
Ignore EvtFormatMessage() errors if data is returned.

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

# Tests
Ran `go test` on Windows server 2022 host:
```
PS C:\Users\Administrator\go\src\github.com\aws\amazon-cloudwatch-agent\plugins\inputs\windows_event_log> go test
C:\Users\ADMINI~1\AppData\Local\Temp\2\CloudWatchAgentTest\Amazon_CloudWatch_WindowsEventLog_MyGroup_MyStream_SystemEventLog
C:\Users\ADMINI~1\AppData\Local\Temp\2\CloudWatchAgentTest\Amazon_CloudWatch_WindowsEventLog_My__Group_____My__Stream_____System__Event__Log__


PASS
ok      github.com/aws/amazon-cloudwatch-agent/plugins/inputs/windows_event_log 0.032s
```
and
```
PS C:\Users\Administrator\go\src\github.com\aws\amazon-cloudwatch-agent\plugins\inputs\windows_event_log> cd .\wineventlog\
PS C:\Users\Administrator\go\src\github.com\aws\amazon-cloudwatch-agent\plugins\inputs\windows_event_log\wineventlog> go test
2022/04/05 20:41:44 I! Buffer used: 2872 is returning as single byte character count
2022/04/05 20:41:44 I! Buffer used: 1436 is returning as double byte character count, doubling it to get the whole buffer content.
2022/04/05 20:41:44 I! Buffer used: 512 is returning as double byte character count, doubling it to get the whole buffer content.
2022/04/05 20:41:44 W! [wineventlog] EvtSubscribe(), name FakeBadElogName, err The specified channel could not be found.
2022/04/05 20:41:44 I! [wineventlog] EvtOpenPublisherMetadata() publisher CWA_UnitTest222, err The system cannot find the file specified.
.
.
.
2022/04/05 20:41:49 I! [wineventlog] EvtOpenPublisherMetadata() publisher CWA_UnitTest222, err The system cannot find the file specified.
2022/04/05 20:41:49 I! [wineventlog] EvtOpenPublisherMetadata() publisher CWA_UnitTest222, err The system cannot find the file specified.
PASS
ok      github.com/aws/amazon-cloudwatch-agent/plugins/inputs/windows_event_log/wineventlog     4.679s
PS C:\Users\Administrator\go\src\github.com\aws\amazon-cloudwatch-agent\plugins\inputs\windows_event_log\wineventlog>
```

Here is the failiure just for reference:
```
PS C:\Users\Administrator\go\src\github.com\aws\amazon-cloudwatch-agent\plugins\inputs\windows_event_log\wineventlog> go test
2022/04/05 23:18:50 I! Buffer used: 2872 is returning as single byte character count
2022/04/05 23:18:50 I! Buffer used: 1436 is returning as double byte character count, doubling it to get the whole buffer content.
2022/04/05 23:18:50 I! Buffer used: 512 is returning as double byte character count, doubling it to get the whole buffer content.
2022/04/05 23:18:50 W! [wineventlog] EvtSubscribe(), name FakeBadElogName, err The specified channel could not be found.
2022/04/05 23:18:50 I! [wineventlog] EvtFormatMessage() publisher CWA_UnitTest111, err The message ID for the desired message could not be found.
2022/04/05 23:18:50 I! [wineventlog] EvtFormatMessage() publisher CWA_UnitTest111, err The message ID for the desired message could not be found.
2022/04/05 23:18:50 I! [wineventlog] EvtFormatMessage() publisher CWA_UnitTest111, err The message ID for the desired message could not be found.
2022/04/05 23:18:50 I! [wineventlog] EvtFormatMessage() publisher CWA_UnitTest111, err The message ID for the desired message could not be found.
2022/04/05 23:18:50 I! [wineventlog] EvtFormatMessage() publisher CWA_UnitTest111, err The message ID for the desired message could not be found.
2022/04/05 23:18:50 I! [wineventlog] EvtFormatMessage() publisher CWA_UnitTest111, err The message ID for the desired message could not be found.
2022/04/05 23:18:50 I! [wineventlog] EvtFormatMessage() publisher CWA_UnitTest111, err The message ID for the desired message could not be found.
2022/04/05 23:18:50 I! [wineventlog] EvtFormatMessage() publisher CWA_UnitTest111, err The message ID for the desired message could not be found.
2022/04/05 23:18:50 I! [wineventlog] EvtFormatMessage() publisher CWA_UnitTest111, err The message ID for the desired message could not be found.
2022/04/05 23:18:50 I! [wineventlog] EvtFormatMessage() publisher CWA_UnitTest111, err The message ID for the desired message could not be found.
.
.
.
--- FAIL: TestReadWithBothSources (2.24s)
    wineventlog_test.go:122: seekToEnd() current count 0
    wineventlog_test.go:128: seekToEnd() total 0
    wineventlog_test.go:175:
                Error Trace:    wineventlog_test.go:175
                                                        wineventlog_test.go:110
                Error:          Not equal:
                                expected: 10
                                actual  : 0
                Test:           TestReadWithBothSources
                Messages:       expected [Application] [ERROR] [777] [CWA_UnitTest111] , 10, actual 0
FAIL
exit status 1
FAIL    github.com/aws/amazon-cloudwatch-agent/plugins/inputs/windows_event_log/wineventlog     5.219s
```

### CODE REVIEW

**Comment by SaxyPandaBear** [comment]
Just for sanity, what was the output of running tests on a Win2022 host before that change? It looks super benign to me, but I'm trying to understand how that impacted the behavior so much that it caused test failures.

File: plugins/inputs/windows_event_log/wineventlog/wineventlog.go [hunk 1]
```diff
@@ -320,7 +320,7 @@ func (w *windowsEventLog) getRecord(evtHandle EvtHandle) (*windowsEventLogRecord
 	var bufferUsed uint32
 	err = EvtFormatMessage(publisherMetadataEvtHandle, evtHandle, 0, 0, 0, EvtFormatMessageXml, uint32(bufferSize), &renderBuf[0], &bufferUsed)
 	EvtClose(publisherMetadataEvtHandle)
-	if err != nil {
+	if err != nil && bufferUsed == 0 {
 		return nil, fmt.Errorf("EvtFormatMessage() publisher %v, err %v", newRecord.System.Provider.Name, err)
 	}
```
Comment (adam-mateen) [inline plugins/inputs/windows_event_log/wineventlog/wineventlog.go:325]: The test was working for Windows Server 2019.
It was failing for Windows Server 2022 with the `err`:
`The message ID for the desired message could not be found`.

It turns out that despite getting an error, `EvtFormatMessage()` was returning the expected message in the `renderBuf` slice.

In my opinion, if data is returned then the `err` is more like a _warning_.
And we should report the event log message if we can.

If desired I could add a message to CloudWatchAgent.log for this scenario:
```
if err != nil {
    log.Printf("D! [wineventlog] EvtFormatMessage() publisher %v, err %v", newRecord.System.Provider.Name, err)
    if bufferUsed == 0 {
        return nil, fmt.Errorf("EvtFormatMessage() publisher %v, err %v", newRecord.System.Provider.Name, err)
    }
}
```
Given that is will probably occur a lot I have chosen not to add it.

**Review by ZhenyuTan-amz — APPROVED** [review]
Good catch on the buff is still getting the data.

**Comment by SaxyPandaBear** [comment]
```
--- FAIL: TestSharedCrednetialsProviderExpiryWindowIsExpired (3.01s)
    refreshable_shared_credentials_provider_test.go:45: 
        	Error Trace:	refreshable_shared_credentials_provider_test.go:45
        	Error:      	Should be true
        	Test:       	TestSharedCrednetialsProviderExpiryWindowIsExpired
        	Messages:   	Expect creds to be expired.
FAIL
```
This looks like a new test failure. I'm assuming it's just flaky but pasting it here for reference

**Review by SaxyPandaBear — APPROVED** [review]
